# Generated by Django 2.2.12 on 2021-02-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UmsAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('icon', models.ImageField(null=True, upload_to='', verbose_name='头像')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='邮箱')),
                ('nick_name', models.CharField(default='', max_length=200, verbose_name='昵称')),
                ('note', models.TextField(null=True, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('login_time', models.DateTimeField(verbose_name='最后登录时间')),
                ('status', models.IntegerField(default=1, verbose_name='帐号启用状态：0->禁用；1->启用')),
            ],
        ),
    ]
