# Generated by Django 2.2.12 on 2021-02-03 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='umsadmin',
            name='login_time',
            field=models.DateTimeField(null=True, verbose_name='最后登录时间'),
        ),
    ]
