# Generated by Django 2.2.12 on 2021-02-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210203_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmsMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.BigIntegerField(null=True, verbose_name='父级ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('title', models.CharField(max_length=100, verbose_name='菜单名称')),
                ('level', models.IntegerField(null=True, verbose_name='菜单级数')),
                ('sort', models.IntegerField(null=True, verbose_name='菜单排序')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='前端名称')),
                ('icon', models.CharField(max_length=150, null=True, verbose_name='前端图标')),
                ('hidden', models.IntegerField(default=0, verbose_name='前端隐藏')),
            ],
        ),
        migrations.CreateModel(
            name='UmsRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='描述')),
                ('admin_count', models.IntegerField(default=0, verbose_name='后台用户数量')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(default=1, verbose_name='启用状态：0->禁用；1->启用')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
            ],
        ),
        migrations.CreateModel(
            name='UmsRoleMenus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_id', models.BigIntegerField(verbose_name='角色id')),
                ('menu_id', models.BigIntegerField(verbose_name='目录id')),
            ],
        ),
    ]
