# Generated by Django 2.2.12 on 2021-02-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_umsmenus_umsrole_umsrolemenus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UmsAdminRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.BigIntegerField(verbose_name='用户id')),
                ('role_id', models.BigIntegerField(verbose_name='角色id')),
            ],
        ),
    ]
