# Generated by Django 2.2.12 on 2021-02-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_umsadminrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UmsAdminRole',
        ),
        migrations.AddField(
            model_name='umsrole',
            name='role_id',
            field=models.BigIntegerField(null=True, verbose_name='角色id'),
        ),
    ]
