# Generated by Django 2.2.12 on 2021-02-16 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210216_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='umsrole',
            name='role_id',
        ),
        migrations.AddField(
            model_name='umsadmin',
            name='role_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UmsRole'),
        ),
    ]
