# Generated by Django 2.2.12 on 2021-02-16 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210216_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='umsadmin',
            old_name='role_id',
            new_name='role',
        ),
    ]
